baseURL: "https://ernestojakobus.github.io/website/"
title: "Río de Oro"

# Lokales Theme aus themes/PaperMod
theme: "PaperMod"

# Für GitHub Pages (Projekt unter /website/)
canonifyURLs: true
relativeURLs: false

# ► Spanisch ist Default, keine Sprach-Unterordner
defaultContentLanguage: es
defaultContentLanguageInSubdir: false

languages:
  es:
    languageName: "Español"
    weight: 1
    title: "Río de Oro"
    contentDir: "content"
    taxonomies:
      category: categorias
      tag: etiquetas
      series: series
  de:
    disabled: true
  en:
    disabled: true

# Navigation ohne harte Root-URLs
menu:
  main:
    - name: Inicio
      pageRef: /
      weight: 1
    - name: Tours
      pageRef: touren          # verweist auf content/touren/_index.md
      weight: 5
    - name: Contacto
      pageRef: kontakt         # content/kontakt/_index.md oder kontakt.md
      weight: 10

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "papermod"]

minify:
  disableXML: true

pagination:
  disableAliases: false
  pagerSize: 5

params:
  env: production
  description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
  author: "Río de Oro"
  defaultTheme: auto

  # PaperMod-Optionen
  ShowShareButtons: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  displayFullLangName: false
  ShowLanguageSwitcher: false

  images:
    - "images/papermod-cover.png"

  # Eigene CSS-Datei
  customCSS:
    - css/custom.css

  # Fingerprinting ausschalten → keine doppelten /website/… Pfade
  assets:
    disableFingerprinting: true

outputs:
  home: [HTML, RSS, JSON]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

# Beispiel-Permalinks nur für "posts"
permalinks:
  posts: "/:slug/"
