baseURL: "https://ernestojakobus.github.io/website/"
title: "Río de Oro"

# Lokales, vendortes Theme (themes/PaperMod)
theme: "PaperMod"

# Hilft auf GitHub Pages (Projekt-Unterordner) gegen 404
canonifyURLs: true
relativeURLs: true

# ► Spanisch ist Default, keine Sprach-Unterordner (/ statt /es/)
defaultContentLanguage: es
defaultContentLanguageInSubdir: false

languages:
  es:
    languageName: "Español"
    weight: 1
    title: "Río de Oro"
    contentDir: "content"
    taxonomies:
      category: categorias
      tag: etiquetas
      series: series
  de:
    disabled: true
  en:
    disabled: true

# Navigation – ohne harte "/"-URLs, stattdessen pageRef (robust für Unterpfade)
menu:
  main:
    - name: Inicio
      pageRef: /
      weight: 1
    - name: Tours
      pageRef: touren
      weight: 5
    - name: Contacto
      pageRef: kontakt
      weight: 10

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "papermod"]

minify:
  disableXML: true

pagination:
  disableAliases: false
  pagerSize: 5

params:
  env: production
  description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
  author: "Río de Oro"
  defaultTheme: auto

  # PaperMod-Optionen
  ShowShareButtons: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  displayFullLangName: false
  ShowLanguageSwitcher: false   # eigener Header, kein PaperMod-Switcher

  images:
    - "images/papermod-cover.png"

  # Nur das, was du wirklich brauchst
  customCSS:
    - css/custom.css
  # customJS: []

outputs:
  home: [HTML, RSS, JSON]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

# Permalinks: Beispiel für posts. Bei dir heißen die Touren "touren" (Section),
# also brauchst du hier NICHTS für die Tour-Seiten. Lass posts so oder entferne es.
permalinks:
  posts: "/:slug/"
