baseURL: "https://ernestojakobus.github.io/website/"
title: "Río de Oro"

theme: "PaperMod"

canonifyURLs: true
relativeURLs: false

defaultContentLanguage: es
defaultContentLanguageInSubdir: false

languages:
  es:
    languageName: "Español"
    weight: 1
    title: "Río de Oro"
    contentDir: "content"
    taxonomies:
      category: categorias
      tag: etiquetas
      series: series
  de:
    disabled: true
  en:
    disabled: true

menu:
  main:
    - name: Inicio
      pageRef: ""          # Startseite relativ, wichtig für /website/
      weight: 1
    - name: Tours
      pageRef: touren
      weight: 5
    - name: Contacto
      pageRef: kontakt     # Seite anlegen oder Menüpunkt entfernen
      weight: 10

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "papermod"]

minify:
  disableXML: true

pagination:
  disableAliases: false
  pagerSize: 5

params:
  env: production
  description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
  author: "Río de Oro"
  defaultTheme: auto

  ShowShareButtons: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  displayFullLangName: false
  ShowLanguageSwitcher: false

  images:
    - "images/papermod-cover.png"

  # ► Statisches Custom-CSS (liegt unter static/css/custom.css)
  customCSS:
    - css/custom.css

  # (Optional) Fingerprinting in PaperMod-Assets abstellen
  assets:
    disableFingerprinting: true

outputs:
  home: [HTML, RSS, JSON]
  section: [HTML]
  page:    [HTML]
  taxonomy: [HTML]
  term:     [HTML]
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

permalinks:
  posts: "/:slug/"
