baseURL: "https://ernestojakobus.github.io/website/"
title: "Río de Oro"

theme: "PaperMod"
canonifyURLs: true
relativeURLs: true

module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod

# ► Spanisch ist Default, keine Sprach-Unterordner (/ statt /es/)
defaultContentLanguage: es
defaultContentLanguageInSubdir: false

languages:
  es:
    languageName: "Español"
    weight: 1
    title: "Río de Oro"
    contentDir: "content"
    taxonomies:
      category: categorias
      tag: etiquetas
      series: series
  de:
    disabled: true
  en:
    disabled: true

# Menü – nutze deine existierenden Routen/Ordnernamen
# (Dein Abschnitt heißt "touren", daher bleibt die URL /touren/)
menu:
  main:
    - name: Inicio
      url: /
      weight: 1
    - name: Tours
      url: /touren/
      weight: 5
    - name: Contacto
      url: /kontakt/
      weight: 10

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "papermod"]

minify:
  disableXML: true

pagination:
  disableAliases: false
  pagerSize: 5

params:
  env: production
  description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
  author: "Río de Oro"
  defaultTheme: auto

  # PaperMod-Optionen
  ShowShareButtons: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  displayFullLangName: false
  ShowLanguageSwitcher: false   # eigener Header, kein PaperMod-Switcher

  images:
    - "images/papermod-cover.png"

  # Nur das, was du wirklich brauchst
  customCSS:
    - css/custom.css
  # customJS: []   # leer lassen, falls nix global eingebunden werden soll

  homeInfoParams:
    Title: "¡Bienvenido a Río de Oro!"
    Content: "🌊 Descubre tours inolvidables en el Río Paraguay."

  socialIcons:
    - name: instagram
      title: Instagram
      url: "https://www.instagram.com/rio_de_oro_lambare/"
    - name: facebook
      title: Facebook
      url: "https://www.facebook.com/profile.php?id=61578929368383"

outputs:
  home: [HTML, RSS, JSON]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

permalinks:
  page:
    posts: "/:contentbasename/"
